.analysis_options
CHANGELOG.md
lib/code_builder.dart
lib/dart/async.dart
lib/dart/core.dart
lib/src/builders/expression.dart
lib/src/builders/expression/assert.dart
lib/src/builders/expression/assign.dart
lib/src/builders/expression/invocation.dart
lib/src/builders/expression/negate.dart
lib/src/builders/expression/operators.dart
lib/src/builders/expression/return.dart
lib/src/builders/field.dart
lib/src/builders/file.dart
lib/src/builders/statement/block.dart
lib/src/builders/statement/if.dart
lib/src/builders/type/new_instance.dart
lib/src/tokens.dart
test/builders/expression_test.dart
test/builders/field_test.dart
test/builders/file_test.dart
test/builders/reference_test.dart
test/builders/shared_test.dart
test/builders/statement_test.dart
test/builders/type_test.dart
test/scope_test.dart
tool/presubmit.sh

- Slight updates to confusing documentation.
- Added support for null-aware assignments.
- Added `show` and `hide` support to `ImportBuilder`
- Added `deferred` support to `ImportBuilder`
- Added `ExportBuilder`
- Added `list` and `map` literals that support generic types
---
Closes https://github.com/dart-lang/code_builder/issues/17
Closes https://github.com/dart-lang/code_builder/issues/18
Closes https://github.com/dart-lang/code_builder/issues/19
Closes https://github.com/dart-lang/code_builder/issues/20
/cc @alorenzen

Various changes to close a bunch of open issues

---

lib/src/builders/class.dart
lib/src/builders/expression.dart
lib/src/builders/expression/assert.dart
lib/src/builders/expression/assign.dart
lib/src/builders/expression/cascade.dart
lib/src/builders/expression/invocation.dart
lib/src/builders/expression/negate.dart
lib/src/builders/expression/operators.dart
lib/src/builders/expression/return.dart
lib/src/builders/field.dart
lib/src/builders/file.dart
lib/src/builders/method.dart
lib/src/builders/parameter.dart
lib/src/builders/reference.dart
lib/src/builders/shared.dart
lib/src/builders/statement.dart
lib/src/builders/statement/block.dart
lib/src/builders/statement/if.dart
lib/src/builders/type.dart
lib/src/builders/type/new_instance.dart
lib/src/scope.dart
pubspec.yaml

The old mechanism for creating analyzer ASTs (factory constructors on
the interface classes) will be going away in analyzer 0.30.

Begin taking advantage of analyzer's new AstFactory class.

---

lib/src/scope.dart

Change Scope.identifier() to make importFrom an optional parameter.
All subclasses of Scope.identifier already do this, so it is inconsistent for the actual interface to not..

Fix inconsistency in scope.dart

---

CHANGELOG.md
lib/code_builder.dart
lib/src/builders/expression.dart
lib/src/builders/expression/operators.dart
lib/src/builders/method.dart
lib/src/builders/parameter.dart
lib/src/builders/statement.dart
lib/src/builders/statement/for.dart
lib/src/builders/statement/while.dart
lib/src/tokens.dart
pubspec.yaml
test/builders/class_test.dart
test/builders/statement_test.dart

_I don't expect anyone to get to this before the new year_
Closes https://github.com/dart-lang/code_builder/issues/50
Closes https://github.com/dart-lang/code_builder/issues/49
Closes https://github.com/dart-lang/code_builder/issues/47
Partial support on https://github.com/dart-lang/code_builder/issues/43
- Add support for `async`, `sync`, `sync*` functions
- Add support for expression `asAwait`, `asYield`, `asYieldStar`
- Add `toExportBuilder` and `toImportBuilder` to types and references
- Fix an import scoping bug in `return` statements and named constructor invocations.
- Added constructor initializer support
- Add `while` and `do {} while` loop support
- Add `for` and `for-in` support
- Added a `name` getter for `ParameterBuilder`
/cc @alorenzen

New features for 1.0.0-beta

---

CHANGELOG.md
lib/src/builders/expression.dart
lib/src/builders/expression/raw.dart
lib/src/builders/statement.dart
lib/src/builders/statement/raw.dart
pubspec.yaml
test/builders/expression_test.dart
test/builders/statement_test.dart

Closes https://github.com/dart-lang/code_builder/issues/51 by parsing expressions and statements (wrapping them in a function), and then using the resulting AST as the result of the builder itself.
Also updates the `CHANGELOG.md` and `pubspec.yaml` for `1.0.0-beta+1`.
/cc @alorenzen

Add support for raw builders

---

CHANGELOG.md
lib/src/builders/class.dart
lib/src/builders/expression.dart
lib/src/builders/expression/assign.dart
lib/src/builders/expression/index.dart
lib/src/builders/expression/yield.dart
lib/src/builders/statement/switch.dart
lib/src/builders/type.dart
test/builders/expression_test.dart
test/builders/method_test.dart
test/builders/type_test.dart

Closes https://github.com/dart-lang/code_builder/issues/62
Closes https://github.com/dart-lang/code_builder/issues/61
Closes https://github.com/dart-lang/code_builder/issues/58
- Allow referring to a `ClassBuilder` and `TypeBuilder` as an expression
- Add support for accessing the index `[]` operator on an expression
- Changed `ExpressionBuilder.asAssign` to always take an `ExpressionBuilder` as
target and removed the `value` property. Most changes are pretty simple, and
involve just using `reference(...)`. For example:
```dart
literal(true).asAssign(reference('flag'))
```
... emits `flag = true`.

Close a bunch of open issues for 1.0.0-beta+1

---

CHANGELOG.md
lib/src/builders/method.dart
pubspec.yaml
test/builders/method_test.dart

`async` identifier name is forbidden within `async` context. For example, the following is illegal Dart code:
```dart
test('illegal', () async {
MethodModifier.async;
});
```

rename MethodModifier constant names

---

CHANGELOG.md
lib/dart/core.dart
lib/src/builders/expression.dart
lib/src/builders/expression/cast.dart
lib/src/builders/expression/invocation.dart
lib/src/builders/type.dart
lib/src/builders/type/new_instance.dart
pubspec.yaml
test/builders/expression_test.dart
test/builders/type_test.dart
test/e2e_test.dart

Closes https://github.com/dart-lang/code_builder/issues/65
Closes https://github.com/dart-lang/code_builder/issues/66
Sorry for the extra breaking changes - but even while updating the tests I found these confusing - and would rather fix now before we have too many users in a stable branch:
- Added support for `genericTypes` parameter for `ExpressionBuilder#invoke`:
```dart
expect(
explicitThis.invoke('doThing', [literal(true)], genericTypes: [
lib$core.bool,
]),
equalsSource(r'''
this.doThing<bool>(true)
'''),
);
```
- Added a `castAs` method to `ExpressionBuilder`:
```dart
expect(
literal(1.0).castAs(lib$core.num),
equalsSource(r'''
1.0 as num
'''),
);
```
- Removed `namedNewInstance` and `namedConstInstance`, replaced with `name: `:
```dart
expect(
reference('Foo').newInstance([], …
```

Add support for generic types in methods and `as` cast

---

README.md

It's already used in a couple projects successfully and we've burned down most of the bugs/usability issues.

Remove references to this being experimental

---

lib/src/builders/expression.dart
test/builders/expression_test.dart

Allows creating string literals like “hello 'world'” and multiline string literals:
var s = '''hello
world''';
This change assumes that users of this package provide string literals like they would provide raw text (`r"text"` in normal Dart). Since we escape `'`, we also escape `\`, and therefore every other magic sequence (including `\n`, `\t` etc.). I think that's a reasonable assumption.

Allow quotes and newlines in string literal

---

CHANGELOG.md
lib/code_builder.dart
lib/src/builders/file.dart
lib/src/builders/method.dart
lib/src/builders/reference.dart
lib/src/builders/type/new_instance.dart
lib/src/tokens.dart
pubspec.yaml
test/builders/file_test.dart
test/builders/method_test.dart

- Renamed `PartBuilder` to `PartOfBuilder`.
- Added a new class, `PartBuilder`, to represent `part '...dart'` directives.
- Added the `HasAnnotations` interface to all library/part/directive builders.
- Added `asFactory` and `asConst` to `ConstructorBuilder`.
- Added `ConstructorBuilder.redirectTo` for a redirecting factory constructor.
- Added a `name` getter to `ReferenceBuilder`.
- Supplying an empty constructor name (`''`) is equivalent to `null` (default).
Closes https://github.com/dart-lang/code_builder/issues/83
Closes https://github.com/dart-lang/code_builder/issues/81
Closes https://github.com/dart-lang/code_builder/issues/78
Partially addresses https://github.com/dart-lang/code_builder/issues/43

Resolve a number of open issues

---

.travis.yml
CHANGELOG.md
README.md
example/animal.dart
example/scope.dart
lib/src/emitter.dart
lib/src/mixins/generics.dart
lib/src/specs/class.dart
lib/src/specs/class.g.dart
lib/src/specs/field.dart
lib/src/specs/field.g.dart
lib/src/specs/method.dart
lib/src/specs/method.g.dart
lib/src/specs/reference.dart
lib/src/specs/type_reference.dart
lib/src/specs/type_reference.g.dart
pubspec.yaml
test/allocator_test.dart
test/e2e/injection_test.dart
test/specs/class_test.dart
test/specs/field_test.dart
test/specs/method_test.dart
tool/build.dart
tool/watch.dart

This makes the API much cleaner without the implicit behavior hurting users.
* Removed `Reference.localScope`. Just use `Reference(symbol)` now.
* Allow `Reference` instead of an explicit `TypeReference` in most APIs.
* `toType()` is performed for you as part the emitter process
```dart
final animal = new Class((b) => b
..name = 'Animal'
// Used to need a suffix of .toType().
..extend = const Reference('Organism')
..methods.add(new Method.returnsVoid((b) => b
..name = 'eat'
..lambda = true
..body = new Code((b) => b..code = 'print(\'Yum\')'))));
```
* We now support the Dart 2.0 pre-release SDKs (`<2.0.0-dev.infinity`)
Closes https://github.com/dart-lang/code_builder/issues/120.

Use Reference instead of TypeReference.

---

CHANGELOG.md
lib/src/emitter.dart
lib/src/specs/code.dart
lib/src/specs/expression.dart
lib/src/specs/expression/invoke.dart
pubspec.yaml
test/specs/code/expression_test.dart
test/specs/file_test.dart

Closes https://github.com/dart-lang/code_builder/issues/135.
Closes https://github.com/dart-lang/code_builder/issues/136.
Closes https://github.com/dart-lang/code_builder/issues/137.
Closes https://github.com/dart-lang/code_builder/issues/138.
Closes https://github.com/dart-lang/code_builder/issues/139.
~~This API already exists internally, so I'm skipping tests until we are back in sync - I won't release this as `2.0.0-alpha+3` before adding test coverage, though.~~ **EDIT**: Added tests anyway.

Fix a number of issues.

---

CHANGELOG.md
lib/src/specs/expression/literal.dart
test/specs/code/expression_test.dart

Closes #155
If there is an unescaped literal in a String the code would otherwise be
invalid.
If some code is doing the escaping before creating the literal this will
end up double-escaping.

Escape single quotes in String literals

---

CHANGELOG.md
lib/src/specs/expression/literal.dart

Since the LiteralListExpression is in the public API we shouldn't change
it's field type, so immediately call .toList()

Accept an Iterable in `literalList`

---

CHANGELOG.md
lib/code_builder.dart
lib/src/matchers.dart
pubspec.yaml
test/allocator_test.dart
test/common.dart
test/e2e/injection_test.dart
test/specs/class_test.dart
test/specs/code/expression_test.dart
test/specs/code/statement_test.dart
test/specs/field_test.dart
test/specs/library_test.dart
test/specs/method_test.dart

The rationale here is to remove a dependency on `dart_style` and `analyzer` in `3.0.0`.
In reality it is only depended on for `equalsDart`, which is only for testing. If in the future we get modular packages or sub packages then it might be worth bringing back in some form, but this likely is to give more flexibility, especially around packages like `analyzer` that are almost impossible to revision against.
I've made the changes to make the tests in _this_ package future-proof.

Add EqualsDart and EqualsDart.format.

---

CHANGELOG.md
lib/code_builder.dart
lib/src/emitter.dart
lib/src/mixins/annotations.dart
lib/src/specs/annotation.dart
lib/src/specs/annotation.g.dart
lib/src/specs/class.dart
lib/src/specs/class.g.dart
lib/src/specs/constructor.dart
lib/src/specs/constructor.g.dart
lib/src/specs/expression.dart
lib/src/specs/field.dart
lib/src/specs/field.g.dart
lib/src/specs/method.dart
lib/src/specs/method.g.dart
lib/src/visitors.dart
test/e2e/injection_test.dart
test/specs/class_test.dart
test/specs/method_test.dart

Largely was just boilerplate over some string-based expression 95%+ of the time.
This change shouldn't be breaking, but will allow us to simply remove `Annotation` in 3.x.

Deprecate the Annotation class.

---

CHANGELOG.md
lib/src/emitter.dart
lib/src/specs/reference.dart
lib/src/specs/type_function.dart
lib/src/specs/type_function.g.dart
lib/src/visitors.dart
test/specs/method_test.dart

Fixes #174
- Add a test which fails before this change and passes after
- Add tests for nested function types since that was untested previously
- Make `FuctionType` implement `TypeReference`, add missing fields
returning null and rebuild the built_value file.
- Return `this` from the `type` getter.

Make `FunctionType` implement `TypeReference`

---

CHANGELOG.md
lib/src/specs/class.g.dart
lib/src/specs/code.g.dart
lib/src/specs/constructor.g.dart
lib/src/specs/directive.g.dart
lib/src/specs/field.g.dart
lib/src/specs/library.g.dart
lib/src/specs/method.g.dart
lib/src/specs/type_function.g.dart
lib/src/specs/type_reference.g.dart
pubspec.yaml

Update `built_value` and regenerate. This is needed to allow `built_value` to upgrade to the latest `builder_runner`.
The newly generated code provides much better error messages on failure to construct an instance, particularly with nested classes.

Upgrade to built_value 5.1.0.

---

lib/src/emitter.dart
lib/src/specs/expression/closure.dart
lib/src/specs/expression/invoke.dart

These four functions are called from libraries _not_ in `test/` or `testing/` directories:
* `toClosure` - called from lib/src/specs/method.dart
* `InvokeExpression.constOf` - called from lib/src/specs/reference.dart
* `InvokeExpression.newOf` - called from lib/src/specs/reference.dart
* `visitAll` - called from lib/src/specs/expression.dart

Remove visibleForTesting annotation for 4 functions

---

README.md
example/example.dart
lib/src/allocator.dart
lib/src/base.dart
lib/src/emitter.dart
lib/src/matchers.dart
lib/src/specs/class.dart
lib/src/specs/code.dart
lib/src/specs/constructor.dart
lib/src/specs/directive.dart
lib/src/specs/expression.dart
lib/src/specs/expression/closure.dart
lib/src/specs/expression/literal.dart
lib/src/specs/field.dart
lib/src/specs/library.dart
lib/src/specs/method.dart
lib/src/specs/reference.dart
lib/src/specs/type_function.dart
lib/src/specs/type_reference.dart
pubspec.yaml
test/allocator_test.dart
test/common.dart
test/e2e/injection_test.dart
test/specs/class_test.dart
test/specs/code/expression_test.dart
test/specs/code/statement_test.dart
test/specs/field_test.dart
test/specs/library_test.dart
test/specs/method_test.dart
tool/src/builder.dart

- Update the SDK constraint to >=2.0.0
- Update README to drop `new` keyword.
- Hold back lib/**/*.g.dart files since they are generated.

Run dartfmt --fix to drop optional new

---

CHANGELOG.md
pubspec.yaml

Updated the lower bound based on running `pub downgrade`.

Bump the dependency range for built_collection

---

CHANGELOG.md
lib/src/emitter.dart
pubspec.yaml
test/specs/method_test.dart

Fixes #232
This follows the recommendations in Effective Dart.

Use `=` instead of `:` for default values

---

lib/src/specs/code.dart
lib/src/specs/expression/literal.dart
lib/src/specs/reference.dart
lib/src/specs/type_function.dart

Update code in Doc comments and text references for Dart 2 style code.

Remove `new` from text references

---

CHANGELOG.md
lib/src/specs/expression/literal.dart
pubspec.yaml
test/specs/code/expression_test.dart

Fixes #241
It is never sensible to write a single quoted string with a newline
character, they should be written as `\n`.

Escape newlines in String literals

---

lib/code_builder.dart
lib/src/specs/expression.dart
lib/src/specs/expression/literal.dart
test/specs/code/expression_test.dart

This pull request adds the `literalSet` and `literalConstSet` functions.
It does the same thing for Sets as `literalList` is doing for Lists.

add support for literal sets

---

lib/src/emitter.dart
test/specs/method_test.dart

Function type with no requiredParameter adds a redundant `,` before
optional positional or named parameters.

fix redundant `,` in Function type

---

lib/src/specs/expression.dart
pubspec.yaml
test/specs/code/expression_test.dart

This pull request adds support for `OR` and `NOT` logical operator expressions.
Previously, there was only an `AND` expression.
For this, we add `Expression.or(Expression)` and `Expression.negate()` methods.
Fixes #247.

`OR` and `NOT` expressions

---

CHANGELOG.md

This PR adds a missing changelog entry for the `3.2.2` version.

Changelog for 3.2.2

---

README.md
build.disabled.yaml

1. `pub run build_runner build` was never happy if my existing foo.dart and foo.g.dart files were not in agreement. Errors like:
```none
Unable to spawn isolate: lib/src/specs/type_reference.g.dart:9:7: Error: The non-abstract class '_$TypeReference' is missing implementations for these members:                                                                                                                                                 
- TypeReference.isNullable                                                                                                                             
Try to either                                                                                                                                           
- provide an implementation, …
```

Update contributing instructions

---

lib/src/emitter.dart
lib/src/specs/type_reference.dart
lib/src/specs/type_reference.g.dart
test/specs/type_reference_test.dart

Fixes #270 
I'm _very_ open on better names to the DartEmitter constructor parameter, `isNullSafety`. The analyzer's LibraryElement has the deprecated name, `isNonNullableByDefault`. WDYT? `hasNullSafety`?
I'd like to have tested a nullable function type, but it didn't seem possible other than setting `symbol` to, e.g. `void Function(int)`.

Add isNullable field to TypeReference, and isNullSafety to DartEmitter

---

lib/src/emitter.dart
test/directive_test.dart

Manually specified directive, most likely exports or part directives,
should generally follow imports. Move imports from `refer` URIs to the
beginning so that they get the correct order as long as manually
specified directives where in the correct order, regardless of sorting
directives.

Sort allocator imports before other directives

---

lib/src/emitter.dart
lib/src/specs/type_function.dart
lib/src/specs/type_function.g.dart
test/specs/code/expression_test.dart

This new field allows FunctionTypes to be written as nullable, using an Emitter that uses null-safety syntax.
Fixes #283

Add an isNullable field to FunctionType

---

CHANGELOG.md
lib/src/specs/expression.dart
pubspec.yaml
test/specs/code/expression_test.dart

Fixes #286 
With this change, an expression can be thrown. This can be done as part of an function expression body, or as a statement, by using `.statement`.

Add a thrown getter to Expression

---

.travis.yml
CHANGELOG.md
pubspec.yaml

Works-around issue with testing Dart 2.6 in CI and changes to
pkg:analyzer
Specifically, it seems there was a change to a non-public analyzer API
that is picked up by packages on Dart 2.6 but the SDK constraint on
`dart_style` prevents picking up a version of that package with the fix.

Bump min Dart SDK to 2.7

---

CHANGELOG.md
lib/src/matchers.dart
pubspec.yaml
test/matcher_test.dart

Fixes #293
When describing a mismatch the _expected_ value should be passed to
`equals`, not the actual value. Also remove the source from the start of
the mismatch description since it's already present in the nested
"Actual" field.
Other refactoring:
- Rename `_source` to `_expectedSource` and `result` to `actualSource`
for clarity.
- Expand the doc comment for `equalsDart`.

Flip expected and actual in mismatch description

---

CHANGELOG.md
lib/src/specs/expression/closure.dart
lib/src/specs/method.dart
pubspec.yaml
test/specs/code/expression_test.dart

Fixes #309 
The existing `closure` getter strips a Method of its return type and type parameters. This new API, `genericClosure` keeps the type parameters, as they are legal, and can be useful.

Add genericClosure on Method

---

lib/src/allocator.dart
lib/src/specs/code.dart
lib/src/specs/reference.dart
lib/src/specs/type_function.dart

The throwing `symbol` getter in `FunctionType` makes it difficult to
perform certain sensible operations, like checking whether a given
reference is to a specific known type.
Rather than impose `is` checks on the call sites who want to read the
`symbol`, make it explicit that not all references have symbols. This
does impose some `!` operators where we use references. This is not any
less safe since an exception would happen either way and we are already
relying on a `FunctionType` not flowing to those call sites.

Make Reference.symbol nullable

---

CHANGELOG.md
lib/src/emitter.dart
test/e2e/injection_test.dart
test/specs/code/expression_test.dart
test/specs/library_test.dart

Fixes https://github.com/dart-lang/code_builder/issues/299
Going with a one-shot approach to keep the same constructor name, it looks feasible to migrate all at once internally and we have a breaking change for NNBD anyways.

change the DartEmitter constructor to use named parameters

---

README.md

The current example of creating a scoped example is incorrect.
This change fixes the example to use the correct constructor.

Fix scoped emitter example in README

---

CHANGELOG.md
lib/src/emitter.dart
lib/src/specs/library.dart
lib/src/specs/library.g.dart
test/specs/library_test.dart

Adds the ability to annotate a `Library` generated by `code_builder`. This is to support scenarios like JavaScript interop using `package:js` where the library itself needs to be annotated with `@JS()`.

Add annotations to libraries

---

CHANGELOG.md
lib/src/specs/expression.dart

Towards #343
The doc showed the argument and the receiver flipped in the output.

Fix docs for Expression.assign

---

CHANGELOG.md
lib/src/emitter.dart
pubspec.yaml
test/specs/field_test.dart

This addresses #370, avoiding late being written out when it would cause a syntax error for non-null-safe parsing.

Only emit 'late' when using null-safety syntax.

---

CHANGELOG.md
lib/src/specs/expression.dart
test/const_test.dart
test/specs/code/expression_test.dart

Point to the relevant `declare*` API which replaces them.

Deprecate assignVar, assignFinal, assignConst

---

CHANGELOG.md
lib/src/emitter.dart
lib/src/specs/expression.dart
test/const_test.dart
test/e2e/injection_test.dart
test/specs/class_test.dart
test/specs/code/expression_test.dart
test/specs/method_test.dart

Fixes https://github.com/dart-lang/code_builder/issues/365
This adds trailing commas in various places according to the following rules:
* in a collection literal if there are more than one element
* in an argument list if there are more than one argument (positional or named)
* in a constructor parameter list, method parameter list, or function type parameter list, if there are more than one parameter (positional, optional, or named)
The last one was certainly the most complex, because of the optional/named delimiters (`[]`/`{}`).
* A parameter list with one positional or one optional or one named parameter does _not_ get a trailing comma.
* A parameter list with multiple positional parameters and no optional or named parameters gets a trailing comma.
* A parameter list with at least one …

Add support for trailing commas in Emitter

---

CHANGELOG.md
lib/src/emitter.dart
pubspec.yaml

This has come up as a point of confusion a few times - by default a `DartEmitter` will not emit any imports. Call out imports in the constructor doc comment.

Mention imports in the DartEmitter docs

---

CHANGELOG.md
pubspec.yaml
test/specs/code/expression_test.dart

Towards #315
Add a skipped test which demonstrates that the nullability of a type
reference is ignored when emitting a variable assignment.

Failing test for assigning to nullable typed var

---

CHANGELOG.md
lib/src/specs/expression.dart
lib/src/specs/expression/literal.dart
pubspec.yaml
test/specs/code/expression_test.dart

Adds a `trailing` parameter which allows the addition of a spread expression. The `Expression` isn't wrapped in a spread automatically because there are two types of spreads.

Add support for spreads in literal

---

lib/code_builder.dart
test/specs/code/expression_test.dart

Add `literalSpread` and `literalNullSafeSpread` to the exports for `expression.dart`.

Show spread literals

---

CHANGELOG.md
lib/code_builder.dart
test/specs/code/expression_test.dart
test/specs/record_type_test.dart

- Fixed changelog entry for records support (records didn't make it to 4.5.0).
- Exported record-related APIs.
---
- See our [contributor guide](https://github.com/dart-lang/.github/blob/main/CONTRIBUTING.md) for general expectations for PRs.
- Larger or significant changes should be discussed in an issue before creating a PR.
- Contributions to our repos should follow the [Dart style guide](https://dart.dev/guides/language/effective-dart) and use `dart format`.
- Most changes should add an entry to the changelog and may need to [rev the pubspec package version](https://github.com/dart-lang/sdk/wiki/External-Package-Maintenance#making-a-change).
- Changes to packages require [corresponding tests](https://github.com/dart-lang/.github/blob/main/CONTRIBUTING.md#Testing).
(note that many Dart …

Fix CHANGELOG.md and export record-related APIs

---

CHANGELOG.md
lib/src/emitter.dart
lib/src/specs/enum.dart
lib/src/specs/enum.g.dart
pubspec.yaml
test/specs/enum_test.dart

- Added support for named arguments in `enum` classes
---
<details>
<summary>Contribution guidelines:</summary><br>
- See our [contributor guide](https://github.com/dart-lang/.github/blob/main/CONTRIBUTING.md) for general expectations for PRs.
- Larger or significant changes should be discussed in an issue before creating a PR.
- Contributions to our repos should follow the [Dart style guide](https://dart.dev/guides/language/effective-dart) and use `dart format`.
- Most changes should add an entry to the changelog and may need to [rev the pubspec package version](https://github.com/dart-lang/sdk/wiki/External-Package-Maintenance#making-a-change).
- Changes to packages require [corresponding tests](https://github.com/dart-lang/.github/blob/main/CONTRIBUTING.md#Testing).
Note that many Dart …

Added support for named arguments in `enum` classes

---

CHANGELOG.md
lib/src/emitter.dart
lib/src/specs/field.dart
lib/src/specs/field.g.dart
test/specs/field_test.dart

- Added support of external keyword for FieldBuilder
-  Issue #409 
- Added test case for external keyword inside field_test
- ```test('should create a external field', () {
expect(
Field((b) => b
..name = 'value'
..external = true
..type = refer('double')
..annotations.addAll([
refer('Float').call([])
])),
equalsDart(r'''
@Float()
external double value;
'''),
);
});

added support of external keyword for field builder

---

CHANGELOG.md
lib/src/specs/expression.dart
pubspec.yaml
test/specs/code/expression_test.dart

I have recently struggled to clean up a package that I maintain using `Expression` operators instead of using `Code` blocks full of strings, i.e. `Code('$a ^ $b')` and have discovered that quite a few operators are missing from the `Expression` class. So I've added all the missing operators and assignments found on https://dart.dev/language/operators.
- added operators
| method | generates |
| :--- | :---: |
| `Expression.operatorIntDivide` | `this ~/ other` |
| `Expression.operatorUnaryPrefixIncrement` | `++this` |
| `Expression.operatorUnaryPostfixIncrement` | `this++` |
| `Expression.operatorUnaryMinus` | `-this` |
| `Expression.operatorUnaryPrefixDecrement` | `--this` |
| `Expression.operatorUnaryPostfixDecrement` | `this--` |
| `Expression.operatorBitwiseAnd` | `this & other` |
| …

Add missing operator and assignment expressions

---

CHANGELOG.md
lib/src/specs/expression/literal.dart
test/specs/code/expression_test.dart

The `LiteralListExpression` allows a mix of Dart values which could be
passed to `literal` and values which are already a `Spec` (typically an
`Expression`). Both types are handled by `_acceptLiteral` in the visitor
implementation.
https://github.com/dart-lang/code_builder/blob/eb70874cf05427879ec47d8726eb3173e11880e3/lib/src/specs/expression.dart#L622-L628
The `toString()` for `LiteralListExpression` calls `literal` on each
value in the list, which previously would throw if it was passed an
`Expression`. Some tests for builders and their implementation details
use `.toString()` in their user facing failure messages. When there is
an exception creating the message for a failure, it can mask the cause
of the failure.
Allow more flexibility for this `toString` by allowing `Expression` …

Allow passing an `Expression` through `literal`

---

CHANGELOG.md
lib/code_builder.dart
pubspec.yaml
test/specs/extension_type_test.dart

RepresentationDeclaration and RepresentationDeclarationBuilder were never exported in 4.8.0. This also cleans up a TODO to use dart format for extension type tests and preps for publish.

Export representation declaration types, upgrade dart_style to 2.3.4, and publish 4.10.0

---

CHANGELOG.md
pubspec.yaml
test/common.dart
test/specs/extension_type_test.dart

- fix a test expectation for extension types (this should address the current CI failure)
- update to the latest `dart_flutter_team_lints`
- catch the correct exception that dart_style throws (note that it doesn't look like this affected any tests)
---
<details>
<summary>Contribution guidelines:</summary><br>
- See our [contributor guide](https://github.com/dart-lang/.github/blob/main/CONTRIBUTING.md) for general expectations for PRs.
- Larger or significant changes should be discussed in an issue before creating a PR.
- Contributions to our repos should follow the [Dart style guide](https://dart.dev/guides/language/effective-dart) and use `dart format`.
- Most changes should add an entry to the changelog and may need to [rev the pubspec package …

fix a test expectation for extension types

---

.github/workflows/test-package.yml
CHANGELOG.md
README.md
analysis_options.yaml
example/example.dart
pubspec.yaml
test/common.dart

We're in [the process of](https://github.com/dart-lang/dart_style/issues/1403) moving dart_style to [a new formatting style](https://github.com/dart-lang/dart_style/issues/1253). That involves making the formatter [aware of the language version of what it's formatting](https://github.com/dart-lang/dart_style/issues/1402).
That in turn means that the library API now lets you pass in a language version. In dart_style 2.3.7 [you can pass in a language version but the parameter is optional](https://pub.dev/documentation/dart_style/latest/dart_style/DartFormatter/DartFormatter.html). In the forthcoming 3.0.0 release, that parameter will become mandatory.
This updates every call to `DartFormatter()` to pass in the latest language version. If there's a more specific version that should be used, …

Update dart_style to pass in a language version to DartFormatter.
