dart-lang/code_builder

lib/src/expression_builder.dart
lib/src/method_builder.dart
lib/src/statement_builder.dart
test/builders/method_builder_test.dart

Closes https://github.com/dart-lang/code_builder/issues/2.

Add Expression#toStatement, and tests.

---

lib/code_builder.dart
lib/src/file_builder.dart
pubspec.yaml
test/builders/file_builder_test.dart
test/integration_test.dart

Closes https://github.com/dart-lang/code_builder/issues/1

Split FileBuilder into LibraryBuilder and PartBuilder

---

CHANGELOG.md
lib/code_builder.dart
lib/src/builders/annotation_builder.dart
lib/src/builders/class_builder.dart
lib/src/builders/constructor_builder.dart
lib/src/builders/expression_builder.dart
lib/src/builders/field_builder.dart
lib/src/builders/file_builder.dart
lib/src/builders/method_builder.dart
lib/src/builders/parameter_builder.dart
lib/src/builders/type_builder.dart
lib/src/scope.dart
lib/testing/equals_source.dart
pubspec.yaml
test/builders/class_builder_test.dart
test/builders/file_builder_test.dart
test/builders/method_builder_test.dart
test/integration_test.dart
test/scope_test.dart

Also ran dartfmt and organized members by name in classes so the diff is much larger than it actually is (sorry about that). Added more tests for when a `Scope` is used.

Add full scoping support for Library

---

README.md
lib/code_builder.dart
lib/src/analyzer_patch.dart
lib/src/builders/class_builder.dart
lib/src/builders/constructor_builder.dart
lib/src/builders/expression_builder.dart
lib/src/builders/file_builder.dart
lib/src/builders/statement_builder.dart
lib/src/pretty_printer.dart
lib/src/scope.dart
pubspec.yaml
test/builders/file_builder_test.dart
test/integration_test.dart
test/scope_test.dart

Closes https://github.com/dart-lang/code_builder/issues/6

Cleanup: Make all ASTs lazy (no _AbstractCodeBuilder)

---

lib/code_builder.dart
lib/src/builders/class_builder.dart
lib/src/builders/constructor_builder.dart
lib/src/builders/expression_builder.dart
lib/src/builders/field_builder.dart
lib/src/builders/file_builder.dart
lib/src/builders/method_builder.dart
lib/src/builders/parameter_builder.dart
lib/src/builders/statement_builder.dart
lib/src/scope.dart
lib/src/tokens.dart
lib/testing/equals_source.dart
pubspec.yaml
test/builders/method_builder_test.dart

Assignment expressions can be either normal or null-aware (using ??=).
This commit also does some cleanup regarding Tokens, moving all Token literals to a shared file.

Add assignment expressions.

---

CHANGELOG.md
lib/src/builders/method.dart
pubspec.yaml
test/builders/file_test.dart
test/builders/method_test.dart

Remove semicolons from where they don't belong.

---

CHANGELOG.md
lib/src/builders/expression/return.dart
lib/src/builders/method.dart
pubspec.yaml
test/e2e_test.dart

forward Scope in returns and constructors

---

test/builders/expression_test.dart
test/builders/method_test.dart

More test cases, useful until we have more docs

---

lib/src/builders/reference.dart
test/e2e_test.dart

Closes https://github.com/dart-lang/code_builder/issues/75

Fix a bug in annotation scoping.

---

CHANGELOG.md
lib/code_builder.dart
lib/src/builders/method.dart
lib/src/builders/parameter.dart
lib/src/builders/type.dart
lib/src/builders/type/type_def.dart
pubspec.yaml
test/builders/class_test.dart
test/builders/parameter_test.dart
test/builders/type_test.dart

Closes https://github.com/dart-lang/code_builder/issues/90
Closes https://github.com/dart-lang/code_builder/issues/92
Closes https://github.com/dart-lang/code_builder/issues/93

More features towards completion

---

.travis.yml
CHANGELOG.md
lib/src/builders/expression.dart
lib/src/builders/expression/ternary.dart
lib/src/tokens.dart
pubspec.yaml
test/builders/expression_test.dart
test/e2e_test.dart
tool/presubmit.sh

Closes https://github.com/dart-lang/code_builder/issues/96

Add ExpressionBuilder#ternary.

---

lib/code_builder.dart
lib/src/builders/file.dart

Closes https://github.com/dart-lang/code_builder/issues/100.

Expose Uri for some builders.

---

test/builders/class_test.dart
test/builders/method_test.dart

Proves https://github.com/dart-lang/code_builder/issues/99 is not needed.

Add tests showing lambda use.

---

CHANGELOG.md
README.md
pubspec.yaml

At this point I mainly imagine community-contributed FRs or backwards-compatible additions.
We should have what we need to create the new Angular compiler, for example.
Thanks to...
- @alorenzen
- @natebosch
- @yjbanov
- @hterkelsen
- @kevmoo
- @zoechi
- @filiph 
- @jimmyff
- @thosakwe 
- @stereotype441 
... for reviews, bug reports, and contributions!

Prepare to release 1.0.0.

---

CHANGELOG.md
pubspec.yaml

Closes https://github.com/dart-lang/code_builder/issues/107

Support latest pkg/analyzer and pkg/func

---

CHANGELOG.md
README.md
example/animal.dart
example/scope.dart
lib/src/specs/method.dart
pubspec.yaml
test/specs/method_test.dart

After this commit, we'll flip merge v2 --> master.
/cc @kevmoo

Prepare to publish 2.0.0-alpha

---

.travis.yml
CHANGELOG.md
README.md
lib/code_builder.dart
lib/src/emitter.dart
lib/src/specs/annotation.g.dart
lib/src/specs/class.g.dart
lib/src/specs/code.g.dart
lib/src/specs/constructor.g.dart
lib/src/specs/directive.dart
lib/src/specs/directive.g.dart
lib/src/specs/field.g.dart
lib/src/specs/file.g.dart
lib/src/specs/method.dart
lib/src/specs/method.g.dart
lib/src/specs/type_reference.g.dart
pubspec.yaml
test/specs/file_test.dart
test/specs/method_test.dart
tool/build.dart
tool/src/codegen.dart
tool/watch.dart

* Closes #123 
* Closes #125 
* Closes #126 
Also updated dependencies around `build_{runner|value|value_generator}`.

Add small set of 2.x milestone fixes.

---

pubspec.yaml

Clean up SDK constraint

---

CHANGELOG.md
lib/code_builder.dart
lib/src/allocator.dart
lib/src/base.dart
lib/src/emitter.dart
lib/src/matchers.dart
lib/src/specs/code.dart
pubspec.yaml
test/specs/code/statement_test.dart

Closes https://github.com/dart-lang/code_builder/issues/145.
Closes https://github.com/dart-lang/code_builder/issues/146.
Closes https://github.com/dart-lang/code_builder/issues/147.

Beta release fixes and feature.

---

CHANGELOG.md
lib/src/specs/expression/literal.dart
pubspec.yaml
test/specs/code/expression_test.dart

Fixes https://github.com/dart-lang/code_builder/issues/151

Add support for raw String in `literalString`

---

lib/src/emitter.dart

... mainly for consistency, based on your feedback earlier.
Closes https://github.com/dart-lang/code_builder/issues/142.

Use .accept not visitFoo where possible.

---

.travis.yml
CHANGELOG.md
pubspec.yaml

Due to function types I think we need this anyway.

Only support 2.0.0-dev.

---

CHANGELOG.md
lib/src/specs/expression.dart
pubspec.yaml
test/specs/code/expression_test.dart

Closes https://github.com/dart-lang/code_builder/issues/159.

Add index operator access to Expression.

---

CHANGELOG.md
lib/src/emitter.dart
pubspec.yaml
test/specs/method_test.dart

(I only need a review from one of you)
Closes https://github.com/dart-lang/code_builder/issues/163.
Will release and sync to Google after this PR.

Fix bug and get ready to release.

---

CHANGELOG.md
lib/src/specs/expression.dart
pubspec.yaml
test/specs/code/expression_test.dart

Add isA and isNotA.

---

CHANGELOG.md
lib/src/specs/constructor.dart
lib/src/specs/constructor.g.dart
pubspec.yaml
test/specs/class_test.dart

Work towards https://github.com/dart-lang/code_builder/issues/180.

Support lambda inference for constructors.

---

pubspec.yaml

Fixes https://github.com/dart-lang/code_builder/issues/184

Support latest built_collection

---

CHANGELOG.md
lib/code_builder.dart
pubspec.yaml

Closes https://github.com/dart-lang/code_builder/issues/188.

Export literalNum.

---

CHANGELOG.md
pubspec.yaml
tool/src/builder.dart

Closes https://github.com/dart-lang/code_builder/issues/195.

Bump for source_gen.

---

lib/src/specs/expression/invoke.dart

Closes https://github.com/dart-lang/code_builder/issues/200.

Run latest dartfmt.

---

README.md

Fixes https://github.com/dart-lang/code_builder/issues/203

Update gitter badge

---

CHANGELOG.md
lib/src/specs/expression.dart
pubspec.yaml
test/specs/code/expression_test.dart

Wrap `as` expressions with parens

---

lib/src/specs/expression.dart
test/specs/code/expression_test.dart

Add Expression.operators (add/substract/divide/multiply/...)

---

build.disabled.yaml
lib/src/specs/class.g.dart
lib/src/specs/code.g.dart
lib/src/specs/constructor.g.dart
lib/src/specs/directive.g.dart
lib/src/specs/field.g.dart
lib/src/specs/library.g.dart
lib/src/specs/method.g.dart
lib/src/specs/type_function.g.dart
lib/src/specs/type_reference.g.dart
pubspec.yaml
tool/src/builder.dart

Also update build_runner and source_gen.
Manually hold back some changes in the generated files - some fields
were missing from `TypeReference`.

Update to latest built_value

---

README.md

Add missing semicolon, use double-quote instead of character esacping

Small tweak to readme

---

CHANGELOG.md
lib/src/specs/expression.dart
pubspec.yaml
test/e2e/injection_test.dart
test/specs/class_test.dart
test/specs/code/expression_test.dart
test/specs/library_test.dart
test/specs/method_test.dart

Don't emit `new` keyword in generated code

---

CHANGELOG.md
lib/src/emitter.dart
lib/src/specs/directive.dart
pubspec.yaml
test/direcive_test.dart

Fixes https://github.com/dart-lang/code_builder/issues/236

Add an option in `DartEmitter` to order directives

---

CHANGELOG.md
README.md
pubspec.yaml

60+ characters makes pub (and SEO) happy

Add more to package description, prepare for v3.2.0

---

CHANGELOG.md
pubspec.yaml

Go back to version 3.2.1

---

.travis.yml
lib/src/allocator.dart
pubspec.yaml

- prefer_collection_literals
Upgrade min SDK to 2.2.0 to allow Set literals.

Fix newly enforced package:pedantic lints

---

.travis.yml
CHANGELOG.md
analysis_options.yaml
lib/src/emitter.dart
lib/src/specs/class.dart
lib/src/specs/class.g.dart
lib/src/specs/code.dart
lib/src/specs/code.g.dart
lib/src/specs/constructor.dart
lib/src/specs/constructor.g.dart
lib/src/specs/directive.dart
lib/src/specs/directive.g.dart
lib/src/specs/expression.dart
lib/src/specs/expression/literal.dart
lib/src/specs/field.dart
lib/src/specs/field.g.dart
lib/src/specs/library.dart
lib/src/specs/library.g.dart
lib/src/specs/method.dart
lib/src/specs/method.g.dart
lib/src/specs/type_function.dart
lib/src/specs/type_function.g.dart
lib/src/specs/type_reference.dart
lib/src/specs/type_reference.g.dart
pubspec.yaml

Re-ran code generation
Bumped min SDK to allow new collection literal features
Cleaned up .travis.yml file

Enable and fix pedantic lints

---

lib/src/emitter.dart
lib/src/specs/method.dart
lib/src/specs/method.g.dart
test/specs/method_test.dart

Add 'required' and 'covariant' bools to Parameter

---

.travis.yml

Explicitly use SDK dartfmt

---

CHANGELOG.md
pubspec.yaml

The features introduced in 3.4.0 are required by Mockito.

Bump to 3.4.0

---

CHANGELOG.md
lib/src/emitter.dart
test/specs/class_test.dart

https://github.com/dart-lang/code_builder/issues/288

fixed const factory constructor

---

lib/code_builder.dart
lib/src/emitter.dart
lib/src/specs/extension.dart
lib/src/specs/extension.g.dart
lib/src/visitors.dart
test/specs/extension_test.dart

Add extension support

---

CHANGELOG.md
pubspec.yaml

There is one other breaking change issue listed which I did not decide to tackle, https://github.com/dart-lang/code_builder/issues/305. If you want to try and address that first we can wait (I don't fully understand it, or the scope/risk of the change).

release 4.0.0

---

CHANGELOG.md
lib/src/specs/extension.dart
pubspec.yaml
test/specs/extension_test.dart

- Fix dev_dependencies
- Remove unneeded imports

unneeded imports

---

CHANGELOG.md
lib/src/specs/expression.dart
test/specs/code/expression_test.dart

Add support for the spread operator `...` when using collections.

Introduce `Expression.spread`

---

CHANGELOG.md
lib/src/specs/expression.dart
test/specs/code/expression_test.dart

Add support for the postfix ! operator

---

CHANGELOG.md
lib/code_builder.dart
lib/src/emitter.dart
lib/src/specs/mixin.dart
lib/src/specs/mixin.g.dart
lib/src/visitors.dart
test/specs/mixin_test.dart

Redo of #263 to latest.
Added the ability to add fields to the `mixin` as well.

Add support for creating `mixin`s

---

CHANGELOG.md
lib/src/specs/expression.dart
test/specs/code/expression_test.dart

Add the null aware variant of the spread operator.

Introduce `Expression.nullSafeSpread`

---

CHANGELOG.md
README.md
lib/code_builder.dart
lib/src/emitter.dart
lib/src/specs/typedef.dart
lib/src/specs/typedef.g.dart
lib/src/visitors.dart
test/specs/method_test.dart

- add support for emitting typedefs

add support for emitting typedefs

---

CHANGELOG.md
pubspec.yaml

- rev the minor version and prep for publishing
This is split off from https://github.com/dart-lang/code_builder/pull/390 (which may need a bit more thought wrt dartfmt perf and google3 diffs).

rev the minor version and prep for publishing

---

.github/workflows/test-package.yml
CHANGELOG.md
lib/code_builder.dart
lib/src/specs/expression.dart
lib/src/specs/expression/binary.dart
lib/src/specs/expression/closure.dart
lib/src/specs/expression/code.dart
lib/src/specs/expression/invoke.dart
lib/src/specs/expression/literal.dart
lib/src/specs/expression/parenthesized.dart
lib/src/specs/reference.dart
pubspec.yaml
test/specs/code/expression_test.dart
test/specs/code/statement_test.dart
test/specs/enum_test.dart

Also some small spelling fixes
Also a todo about an incorrectly spelled function

Require Dart 2.19, update to and fix latest lints

---

.github/workflows/publish.yaml
CHANGELOG.md
pubspec.yaml

Add publish workflow for github actions.
Drop `-dev` version suffix.

Prepare to publish

---

CHANGELOG.md
lib/code_builder.dart
lib/src/emitter.dart
lib/src/specs/class.dart
lib/src/specs/class.g.dart
lib/src/specs/mixin.dart
lib/src/specs/mixin.g.dart
pubspec.yaml
test/specs/class_test.dart
test/specs/mixin_test.dart

An attempt at adding class modifiers in a non-breaking way.
Outstanding questions:
- Is the validation and/or API enough to encourage proper use?
- Are the tests sufficient for the changes?
---
- See our [contributor guide](https://github.com/dart-lang/.github/blob/main/CONTRIBUTING.md) for general expectations for PRs.
- Larger or significant changes should be discussed in an issue before creating a PR.
- Contributions to our repos should follow the [Dart style guide](https://dart.dev/guides/language/effective-dart) and use `dart format`.
- Most changes should add an entry to the changelog and may need to [rev the pubspec package version](https://github.com/dart-lang/sdk/wiki/External-Package-Maintenance#making-a-change).
- Changes to packages require [corresponding …

Class modifiers

---

.github/workflows/publish.yaml

Drop package name tag prefix for workflow

---

.github/workflows/test-package.yml
CHANGELOG.md
lib/code_builder.dart
lib/src/emitter.dart
lib/src/mixins/annotations.dart
lib/src/mixins/dartdoc.dart
lib/src/mixins/generics.dart
lib/src/specs/code.dart
lib/src/specs/expression.dart
lib/src/specs/extension_type.dart
lib/src/specs/extension_type.g.dart
lib/src/visitors.dart
pubspec.yaml
test/specs/extension_test.dart
test/specs/extension_type_test.dart

Corresponds to the syntax defined in https://github.com/dart-lang/language/blob/main/accepted/future-releases/extension-types/feature-specification.md#syntax.

Add support for extension types
